GET http://localhost:3000/api/products/


###
GET http://localhost:3000/api/products/v2

###
GET http://localhost:3000/api/products/v2

###
POST http://localhost:3000/api/products/v2
Content-Type: application/json

{
    "name": "Pantalón de pana",
    "description": "Mu fresquito",
    "price": 60,
    "category": "moda"
}

###
PUT http://localhost:3000/api/products/5
Content-Type: application/json

{
    "name": "Pantalón de pana",
    "description": "Mu fresquito para el veranito",
    "price": 170,
    "category": "moda"
}

###
DELETE http://localhost:3000/api/products/3

###1
GET http://localhost:3000/api/products/cat/moda

###
GET http://localhost:3000/api/clients
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwiZXhwaXJlZF9hdCI6MTYyNjY5NDk5NSwiY3JlYXRlZF9hdCI6MTYyNjY5NDY5NSwicm9sZSI6IlIiLCJpYXQiOjE2MjY2OTQ2OTV9.f24yhWWD5ytjaldJB-o4sCv2Tf9YGHmWfv9ruWzQ3-8

###
POST http://localhost:3000/api/clients



###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "Mario",
    "email": "mario@gmail.com",
    "password": "Admin123!"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "mario@gmail.com",
    "password": "Admin123!"
}

###
GET http://localhost:3000/api/clients/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMywiZXhwaXJlZF9hdCI6MTYyNzEzNDgyNCwiY3JlYXRlZF9hdCI6MTYyNjcwMjgyNCwicm9sZSI6IlIiLCJpYXQiOjE2MjY3MDI4MjR9.kymg2NJIZtKq-oYt83Otehle3_jNBwfmBhB8jq-SlRE

###
GET http://localhost:3000/api/public_products

###
GET http://localhost:3000/api/public_products/1

###
GET http://localhost:3000/api/public_products/cat/moda

###
GET http://localhost:3000/api/users

